=== Reuniões com seu supervisor

Para melhor detalhar o planejamento de suas atividades de estágio, é
importante que você realize reuniões com seu supervisor ou
com profissionais da escola indicados por ele e que vivencie o dia-a-dia
escolar.

.Sugestões para ajudar no detalhamento do seu planejamento
****
* Peça exemplos de planos de aula de professores da escola;
* Verifique conteúdos interessantes a trabalhar em alguma aula de informática;
* Identifique se há professores que se interessariam no
seu apoio para introduzir o uso das TICs no ensino de outras
disciplinas;
* Acompanhe algumas aulas e sinta a realidade dos alunos e da
escola;
* Faça um levantamento junto aos alunos de sua familiaridade/vivência
com recursos computacionais (computadores, _tablets_, _smart phones_, Internet, etc);
* Observe os recursos tecnológicos que vêm sendo usados e
os que poderiam ser utilizados.
****

=== Seleção de Materiais

A medida em que você observa a realidade da escola e conhece mais
o(s) professor(es) com que irá trabalhar de perto, é importante
ir selecionando materiais que podem ser úteis nas suas
ações na escola.

.Dicas para a seleção de materiais
****
* Procure objetos de aprendizagem (vídeos/animações/jogos…) que
podem ser explorados em diferentes aulas;
* Explore repositórios de objetos de aprendizagem e sites
de propósito educacional, como o RIVED (http://rived.mec.gov.br/), o
Portal do Professor (http://portaldoprofessor.mec.gov.br/)
e a Revista Nova Escola (http://revistaescola.abril.com.br/)
* Procure exemplos de materiais e aulas que podem ser úteis na preparação
do plano de aula que você deverá preparar;
* Considerando a realidade da escola, selecione os materiais mais adequados,
observando aspectos como a faixa etária dos alunos com os
quais irá lidar no seu estágio.
****


=== Preparando um Plano de Aula ou Sequência Didática

Inspire-se em planos existentes e construa o seu...
