== Capítulo 1 - Estagiando na Escola


.Objetivos do capítulo


Ao final deste capítulo você será capaz de:


1. *Lembrar* do perfil de egresso do curso de Licenciatura em Ciência da Computação (LC) e das competências esperadas para este profissional, *reconhecendo* atividades que ele pode desempenhar nos ambientes escolares.


2. *Entender* o seu papel como estagiário na escola, *exemplificando* ações que pode desenvolver durante seu estágio.


3. *Analisar* a importância do profissional egresso em LCC na escola e seus desafios *concluindo* esta análise com o levantamento de ações de impacto que podem ser desenvolvidas na escola com a sua ajuda como estagiário.




=== 1.1 O perfil do egresso do curso de Licenciatura em Computação (LC)


Em breve você terá concluído o seu curso superior e será um Licenciado em Ciência da Computação. Você já parou para pensar ou leu sobre quais as *competências* esperadas para este profissional?


Um dos documentos onde você pode encontrar essa informação é o Projeto Pedagógico de Curso (PPC) referente ao curso de Licenciatura em Computação (LC) da UFPB. Neste documento podem ser observados os objetivos do curso, o perfil previsto para egresso e também suas competências esperadas. Você pode baixar este documento a partir do seguinte link: http://goo.gl/VJ0ZOm[c] 




De maneira geral, observa-se que o _curso de Licenciatura em Computação visa formar educadores para atuar nas escolas (de nível fundamental, médio e educação profissional) e nas empresas (qualificando seus funcionários para o trabalho)_. O PPC destaca ainda que seus egressos devem ser _"agentes capazes de promover um espaço para a interdisciplinaridade, a comunicação e a articulação, entre as diversas disciplinas e áreas do conhecimento do currículo escolar"_.


Espera-se que os profissionais egressos do curso de LC _sejam capazes de compreender e aplicar ferramentas tecnológicas disponíveis no mercado, principalmente na área de educação, e que dominem técnicas pedagógicas e os processos de aprendizagem em informática no ensino fundamental, médio, profissionalizante e corporativo_. 


Ainda conforme o PPC do curso, é importante observar as competências esperadas para um profissional licenciado em Computação. De maneira geral, o profissional egresso do curso deve apresentar habilidades e competências para:


*  Especificar os requisitos pedagógicos na interação humano-computador;
* Especificar e *avaliar softwares e equipamentos para aplicações educacionais* e de Educação a Distancia;
* Projetar e desenvolver softwares e hardware educacionais e de educação à distância em equipes interdisciplinares;
* *Atuar junto ao corpo docente das Escolas nos níveis da Educação Básica e Técnico e suas modalidades e demais organizações no uso efetivo e adequado das tecnologias da educação*;
* *Produzir material didático*;
* *Administrar laboratórios de informática para fins educacionais*;
* *Atuar como agentes integradores promovendo a acessibilidade digital*;
* *Atuar como docente com a visão de avaliação crítica e reflexiva*;
* *Propor, coordenar e avaliar, projetos de ensino-aprendizagem assistidos por computador que propiciem a pesquisa*.


        Na disciplina de Estágio 2 teremos como objetivo promover ações que habilitem você a se aprimorar nessas competências em *negrito*.
 
        Você deve ter observado que em algumas escolas nem sempre são explorados nas disciplinas alguns recursos existentes das TICs e que poderiam facilitar o processo de ensino-aprendizagem, ou pelo menos atrair mais os alunos para a educação. 
Além disso, em algumas escolas existem laboratórios de informática, mas nem sempre estes são utilizados. Em alguns casos isso se dá pela falta de profissionais competentes para administrá-los e para propor intervenções pedagógicas que apoiem diferentes disciplinas ou que promovam a própria inclusão digital dos estudantes, ou que desenvolvam seu raciocínio lógico com o ensino de diferentes aspectos da informática.



Você já se imaginou sendo um agente transformador em uma escola e desenvolvendo ações como essas?


Na disciplina de Estágio 2 estaremos focados em ações que egressos de LC poderão desempenhar na escola, e principalmente no nível *fundamental* de ensino. Vê-se que o egresso pode tanto atuar como agente promotor da interdisciplinaridade, explorando recursos de Tecnologia da Informação e Comunicação (TIC) no processo de ensino-aprendizagem quanto ensinando informática (uso de aplicativos, dispositivos tecnológicos e da Internet, ensino de lógica, de programação básica, de desenvolvimento de jogos simples, ensino de computação como ciência abordando conceitos básicos como algoritmos de ordenação e representação da informação, etc). Estes dois caminhos principais (mas não os únicos) que o egresso de LC pode seguir estão ilustrados pela Figura 1.


 Slide1.jpg 


Figura 1 - Possíveis funções que o egresso em LC pode desempenhar na Escola


Considerando sua experiência na disciplina de Estágio 1, onde você pôde observar e analisar a realidade de alguma escola, reflita e responda as seguintes questões:


.Para Refletir e Responder
****
1. A escola precisa desses agentes capazes de promover o uso de ferramentas tecnológicas em diversas disciplinas com fins educacionais? Que atividades poderiam promover esses agentes?
2. O que de informática poderia ser ensinado aos alunos no ensino fundamental ou médio? Por quê?
****




1.2 Exemplos de ações do estagiário em LCC nas Escolas


Observando as competências esperadas para um profissional licenciado em Ciência da Computação (você em breve), diversas ações podem ser desenvolvidas ao longo de um estágio no contexto escolar. Algumas delas são sugeridas a seguir e poderão variar bastante dependendo do nível de ensino em que se irá trabalhar. Ao desenvolver tais ações, você estará recebendo a formação técnica, profissional, científica, humana e social esperada para um licenciado em Ciência da Computação. Embora sejam listadas a segior algumas possíveis ações a desenvolver como sugestões, podem ser desenvolvidas muitas outras atividades, desde que o foco seja a formação do profissional de LCC que atua no ensino básico, e que é o objetivo principal do Estágio 2 em LCC.


1.2.1 Planejamento e execução de um projeto de ensino-aprendizagem multidisciplinar que explore recursos de informática


Prega-se muito o uso da pedagogia de projetos [TODO: REF], em que muito se incentiva o desenvolvimento de projetos com ações envolvendo diversos professores e até a escola como um todo. Como aluno de licenciatura em computação, um bom estágio poderia ser o planejamento de um projeto envolvendo diversas disciplinas e onde diferentes recursos de informática podem ser explorados para atrair os alunos e envolvê-los no projeto.
Exemplos de recursos que podem ser explorados são: grupos e fan pages em redes sociais como Facebook, criação de blogs, criação de sites, uso de câmeras digitais e celulares para registrar fatos do cotidiano e os passos do projeto, uso de softwares educacionais em aulas (podendo aí se explorar tanto softwares projetados para fins educacionais, como outros tipos de software, não obrigatoriamente projetados para este fim, mas que podem ser explorados no processo de ensino-aprendizagem), etc.
Para o desenvolvimento de um projeto multidisciplinar é importante pensar em um tema que seja interessante e que possa ser trabalhado por diferentes professores e ter o apoio desses professores tanto no planejamento quanto na execução do projeto. O planejamento de um projeto assim envolve a definição do tema, justificativa para sua escolha, definição das disciplinas envolvidas, conteúdos trabalhados, atividades planejadas para cada uma e recursos de tecnologia ou não que serão explorados em cada atividade.


1.2.2 Planejamento e execução de um projeto pedagógico que explore recursos de TIC em uma única disciplina 


1.2.3 Organização e administração de laboratórios de informática para fins educacionais
 
1.2.4 Desenvolvimento de materiais instrucionais utilizando recursos tecnológicos disponíveis junto ao corpo docente da escola
 
1.2.5 Levantamento, catalogação e avaliação de objetos de aprendizagem que podem auxiliar os professores da escola
 
1.2.6 Ensino de informática básica
 
1.2.7 Ensino de lógica básica
 
1.2.8 Ensino do pensamento computacional e algorítmico
 
1.2.9 Ensino introdutório de programação
 
1.2.10 Ensino de desenvolvimento de jogos
 
1.2.11 Ensino de robótica
 
1.2.12 Ensino de computação como ciência básica (algoritmos de ordenação, representação da informação e procedimentos computacionais, computação desplugada, etc)
 
 
1.3 Possíveis dificuldades encontradas durante o estágio e como superá-las
 
1.3.1 A falta de apoio ou de motivação de outros professores
 
1.3.2 Desvios de função
 
1.3.3 Falta de motivação dos alunos
 
1.3.4 Pouca experiência com os recursos tecnológicos que irá explorar no estágio
 




== Capítulo 2 -  Planejando o seu estágio


.Objetivos do capítulo
____
Ao final deste capítulo você será capaz de:
1. *Lembrar* do perfil de egresso do curso de Licenciatura em Ciência da Computação (LC) e das competências esperadas para este profissional, *reconhecendo* atividades que ele pode desempenhar nos ambientes escolares.
2. *Entender* o seu papel como estagiário na escola, *exemplificando* ações que pode desenvolver durante seu estágio.
3. *Analisar* a importância do profissional egresso em LCC na escola e seus desafios *concluindo* esta análise com o levantamento de ações que podem ser desenvolvidas na escola com a sua ajuda como estagiário.
5. *Avaliar* aulas observadas na escola *checando* se poderiam receber melhorias com sua intervenção.
6. *Criar* uma esboço de um projeto pedagógico *planejando* seu estágio com ações como aulas que explorem recursos de TIC ou o ensino de informática.
____

                Para obter o sucesso em qualquer atividade que se desenvolva, é necessário um bom planejamento.
 
2.1 Atuando como agente mediador do uso da informática na educação
 
2.2 Atuando como professor de computação

Capítulo 3 -  Avaliando o impacto do seu estágio na escola
 
 

Bibliografia
 
TAJRA, Sanmya Feitosa. Informática na Educação: novas ferramentas pedagógicas para o professor na atualidade. 9. ed. rev., atual. e ampl. São Paulo: Érica, 2012.
[a]Não precisa deste histórico de versão... isto faremos no PDF.
[b]Beleza. É pra eu mesma ter um controle das versões por enquanto.
[c]Depois alterar este link.
