[[prefacio]]
[preface]
== Prefácio

:cap: prefacio
:online: {gitrepo}/blob/{edition}/livro/code/{cap}
:local: code/{cap}

Seja bem-vindo(a) à disciplina de Estágio 2 do Curso de Licenciatura em Computação, onde você continuará a observar a escola, mas poderá também realizar atividades lá aproveitando a formação que tem recebido no curso.

Neste livro iremos detalhar melhor as competências esperadas para um egresso do curso de Licenciatura em Computação e discutiremos algumas ideias de atividades que podem ser desenvolvidas no Estágio 2 para desenvolver em você tais competências.

Esperamos que as ideias aqui apresentadas lhe sejam úteis no planejamento, execução e avaliação de suas ações como estagiário de Licenciatura em Computação na escola.

A seguir apresentaremos alguns aspectos importantes que você deverá observar quando estiver lendo este livro.

[[caixas_de_dialogo]]
=== Caixas de diálogo

Nesta seção apresentamos as caixas de diálogo que poderão ser
utilizadas durante o texto. Confira os significados delas.

[NOTE]
========
Esta caixa é utilizada para realizar alguma reflexão.
========

[TIP]
========
Esta caixa é utilizada quando desejamos dar alguma dica.
========

[IMPORTANT]
========
Esta caixa é utilizada para chamar atenção sobre algo importante.
========


[CAUTION]
========
Esta caixa é utilizada para alertar sobre algo que merece um pouco de cautela.
========
//TODO: Ver porque a imagem está sendo a mesma.

[WARNING]
========
Esta caixa é utilizada para alertar sobre algo que merece cuidado.
========


=== Compreendendo a proposta instrucional do livro

Cada capítulo do livro apresenta objetivos, o conteúdo e discussões para lhe ajudar a atingir os objetivos esperados e algumas atividades, que você pode realizar em arquivos a parte, conforme será explicado adiante.

////
//TODO: Ver se deve ser adicionada essa parte futuramente.
==== Realizando uma atividade no computador

:atividade: https://raw.githubusercontent.com/edusantana/estagio2-lcc-livro/{edition}/atividades/cap1-atividades.docx

//TODO(Ayla): Ver problema com este link

++++
<simpara>
<ulink url="{atividade}">
<inlinemediaobject>
<imageobject>
<imagedata fileref="images/pagina-com-atividade.svg"/>
</imageobject>
</inlinemediaobject></ulink></simpara>
++++

Se você estiver acessando a versão digital deste livro, *clique*
no ícone acima.

[NOTE]
====

Se você tiver acesso à Internet, será iniciado o download
de um arquivo contendo uma atividade. Você poderá utilizar este
arquivo para registrar suas respostas da atividade.

====

[TIP]
====

*Você pode baixar todos os arquivos de atividades
de uma única vez acessando*: {gitrepo}/archive/{edition}.zip

Depois de baixar e descompactar o arquivo, você poderá encontrar os arquivos
de atividades na pasta `atividades`.

====

NOTE: Desta forma, você sempre poderá realizar as atividades propostas,
seja no computador ou no papel.

////


==== Compreendendo os objetivos de aprendizagem

Você observará que no início de cada capítulo serão apresentados seus objetivos
de aprendizagem. Cada objetivo dará origem a uma ou mais atividades.

Por exemplo, o primeiro objetivo de aprendizagem do livro seria:

____

Ao final deste capítulo você será capaz de:

1. *Lembrar* do perfil de egresso do curso de Licenciatura em Ciência
da Computação (LC) e das competências esperadas para este
profissional, *reconhecendo* quais competências poderão ser
desenvolvidas no ambiente escolar durante o Estágio 2.

____

Observando esse objetivo você saberá que o capítulo irá discutir sobre _o perfil do egresso e as competências
esperadas para este profissional_. Em seguida, virá o momento de você verificar
se você está atingindo o objetivo proposto:  *_reconhecendo_* _quais competências
poderão ser desenvolvidas no ambiente escolar durante o Estágio 2_.

////
TIP: Lembre-se que você poderá realizar no papel ou no
computador esta atividade que tem o propósito de verificar se os objetivos de aprendizagem foram alcançados.
Para isso, basta clicar nos ícones da atividade, como você fez
anteriormente.
////

==== Resposta Comentada

Quando uma atividade é proposta, a próxima página irá conter uma
*resposta comentada* seguida de um *feedback*.

Não há mal em avançar direto para as respostas comentadas, mas faça um esforço para só analisá-las depois de tentar
produzir suas próprias respostas.

De forma geral, ao realizar as atividades, você estará se
envolvendo melhor com os assuntos estudados e isso facilitará a assimilação deles.
Portanto, *a realização das atividades é altamente recomendada*.

//TODO: INCLUIR UMA SEÇÃO SOBRE A ORGANIZAÇÃO DO LIVRO QUANDO ELE TIVER SIDO CONCUÍDO

////
Sempre terminar o arquivo com uma nova linha.
////

////
Sempre terminar o arquivo com uma nova linha.
////
