[[prefacio]]
[preface]
== Prefácio

:cap: prefacio
:online: {gitrepo}/blob/{edition}/livro/code/{cap}
:local: code/{cap}

=== Compreendendo a proposta instrucional do livro

==== Realizando uma atividade no computador

:atividade: https://raw.githubusercontent.com/edusantana/estagio2-lcc-livro/{edition}/atividades/cap1-atividades.docx

++++
<simpara>
<ulink url="{atividade}">
<inlinemediaobject>
<imageobject>
<imagedata fileref="images/pagina-com-atividade.svg"/>
</imageobject>
</inlinemediaobject></ulink></simpara>
++++

Se você estiver acessando a versão digital deste livro, *clique*
nos ícones acima. *Faça isso agora!*

NOTE: Se você tiver acesso à internet, será iniciado o download
de um arquivo contendo uma atividade. Você poderá utilizar este
arquivo para registrar suas respostas da atividade.

image::images/icones.svg[scaledwidth="50%"]

[TIP]
====

*Você pode baixar todos os arquivos de atividades
de uma única vez acessando*: {gitrepo}/archive/{edition}.zip

Depois de baixar e descompactar o arquivo, você encontrar os arquivos
de atividades na pasta `atividades`.

====

NOTE: Desta forma você sempre poderá realizar as atividades propostas,
seja no computador ou no papel.

==== Resposta Comentada

Quando uma atividade é proposta, a próxima página irá conter uma
*resposta comentada* seguida de um *feedback*.

Não há mal em avançar direto para as respostas comentadas, na 
realidade elas estão logo na próxima página pois caso você tenha pouco
tempo para os estudos poderá ter acesso rápido às respostas.

Mas de forma geral, ao realizar as atividades você estará se 
envolvendo com os assuntos estudados, facilitando a assimilação deles.
Portanto, *a realização das atividades é altamente recomendada*.

==== Compreendendo os objetivos de aprendizagem

No início de cada capítulo, são apresentados seus objetivos 
de aprendizagem. Cada objetivo dará origem a uma ou mais atividades.

Por exemplo, o primeiro objetivo de aprendizagem do livro seria:

____

Ao final deste capítulo você será capaz de:

1. *Lembrar* do perfil de egresso do curso de Licenciatura em Ciência
da Computação (LC) e das competências esperadas para este
profissional, *reconhecendo* quais competências poderão ser
desenvolvidas no ambiente escolar durante o estágio 2.

____

O capítulo irá abordar o assunto sobre _o perfil do egresso e as competências
esperadas para este profissional_. Em seguida, virá o momento de você verificar
se você está atingindo o objetivo proposto:  *_reconhecendo_* _quais competências 
poderão ser desenvolvidas no ambiente escolar durante o estágio 2_.


TIP: Lembre-se que você poderá realizar esta atividade no papel ou no
computador, clicando nos ícones da atividade, como você fez 
anteriormente.


////
Sempre terminar o arquivo com uma nova linha.
////

